version: '3.4'

services:
  imagesearchengine:
    image: imagesearchengine
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn course.image_processing_api:app --host 0.0.0.0 --port 7000"]
    ports:
      - 7000:7000
      - 5678:5678
